productions = {
    "Program": {"Declaration Program_Tail", "Statement Program_Tail"},
    "Program_Tail": {"Program", "ε"},
    "Declaration": {"Variable_Declaration", "Function_Definition"},
    "Variable_Declaration": {"Type Identifier Variable_Declaration_Tail"},
    "Variable_Declaration_Tail": {"End_Line", "= Expression End_Line", "[ Number ] Variable_Array_Tail"},
    "Variable_Array_Tail": {"End_Line", "= { Array_Values } End_Line"},
    "Type": {"int", "float", "char", "string", "bool", "big int", "double", "small int"},
    "Array_Values": {"Expression Array_Values_Tail"},
    "Array_Values_Tail": {", Expression Array_Values_Tail", "ε"},
    "Function_Definition": {"function Identifier ( Parameters ) { Program }"},
    "Parameters": {"Parameter Parameters_Tail"},
    "Parameters_Tail": {", Parameter Parameters_Tail", "ε"},
    "Parameter": {"Type Identifier Parameter_Tail"},
    "Parameter_Tail": {"{ }", "= Expression", "ε"},
    "Statement": {"Assignment", "If_Statement", "While_Statement", "For_Statement", "Return_Statement", "Function_Call", "Print"},
    "Assignment": {"Identifier = Expression End_Line"},
    "If_Statement": {"if ( Conditions ) { Program } If_Statement_Tail"},
    "If_Statement_Tail": {"Else_If_Statements Optional_Else"},
    "Else_If_Statements": {"Else_If_Statement Else_If_Statements", "ε"},
    "Else_If_Statement": {"elseif ( Conditions ) { Program }"},
    "Optional_Else": {"Else_Statement", "ε"},
    "Else_Statement": {"else { Program }"},
    "While_Statement": {"while ( Conditions ) { Program }"},
    "For_Statement": {"for ( Parameters ; Conditions ; Assignment ) { Program }"},
    "Return_Statement": {"return Expression End_Line"},
    "Function_Call": {"Identifier ( Arguments ) End_Line"},
    "Arguments": {"Expression Arguments_Tail"},
    "Arguments_Tail": {", Expression Arguments_Tail", "ε"},
    "Expression": {"Term Expression_Tail"},
    "Expression_Tail": {"+ Term Expression_Tail", "- Term Expression_Tail", "ε"},
    "Term": {"Factor Term_Tail"},
    "Term_Tail": {"* Factor Term_Tail", "/ Factor Term_Tail", "ε"},
    "Factor": {"Identifier", "Number", "string_literal", "( Expression )"},
    "Conditions": {"Condition Conditions_Tail"},
    "Conditions_Tail": {"&& Condition Conditions_Tail", "|| Condition Conditions_Tail", "ε"},
    "Condition": {"Expression Relational_Operator Expression"},
    "Relational_Operator": {"==", "!=", "<", "<=", ">", ">="},
    "Print": {"print ( Expression ) End_Line"},
    "End_Line": {";"},
    "Identifier": {"id"},
    "string_literal": {"str"},
    "Number": {"num"}
}




FIRST = {
    "Program_Tail": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Variable_Declaration_Tail": {"=", "{", ";"},
    "Variable_Array_Tail": {"=", ";"},
    "Type": {"int", "float", "char", "string", "bool", "big", "double", "small"},
    "Array_Values_Tail": {",", "ε"},
    "Function_Definition": {"function"},
    "Parameters_Tail": {",", "ε"},
    "Parameter_Tail": {"[", "=", "ε"},
    "If_Statement": {"if"},
    "Else_If_Statements": {"ε", "elseif"},
    "Else_If_Statement": {"elseif"},
    "Optional_Else": {"ε", "else"},
    "Else_Statement": {"else"},
    "While_Statement": {"while"},
    "For_Statement": {"for"},
    "Return_Statement": {"return"},
    "Arguments_Tail": {",", "ε"},
    "Expression_Tail": {"+", "-", "ε"},
    "Term_Tail": {"*", "/", "ε"},
    "Factor": {"(", "id", "str", "num"},
    "Conditions_Tail": {"&&", "ε", "(", "id", "str", "num"},
    "Relational_Operator": {"==", "!=", "<", "<=", ">", ">="},
    "Print": {"print"},
    "End_Line": {";"},
    "Identifier": {"id"},
    "string_literal": {"str"},
    "Number": {"num"},
    "Variable_Declaration": {"int", "float", "char", "string", "bool", "big", "double", "small"},
    "Parameter": {"int", "float", "char", "string", "bool", "big", "double", "small"},
    "Assignment": {"id"},
    "Function_Call": {"id"},
    "Declaration": {"int", "float", "char", "string", "bool", "big", "double", "small", "function"},
    "Parameters": {"int", "float", "char", "string", "bool", "big", "double", "small"},
    "Statement": {"id", "while", "return", "print", "if", "for"},
    "If_Statement_Tail": {"ε", "elseif"},
    "Term": {"(", "id", "str", "num"},
    "Program": {"int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Expression": {"(", "id", "str", "num"},
    "Array_Values": {"(", "id", "str", "num"},
    "Arguments": {"(", "id", "str", "num"},
    "Condition": {"(", "id", "str", "num"},
    "Goal": {"int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Conditions": {"(", "id", "str", "num"}
}


FOLLOW = {
    "Goal": {"$"},
    "Program": {"}", "$"},
    "Program_Tail": {"}", "$"},
    "Declaration": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Variable_Declaration": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Variable_Declaration_Tail": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Variable_Array_Tail": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Type": {"id"},
    "Array_Values": {"}"},
    "Array_Values_Tail": {"}"},
    "Function_Definition": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Parameters": {")" , ';'},
    "Parameters_Tail": {")" , ';'},
    "Parameter": {",", "ε"},
    "Parameter_Tail": {",", "ε"},
    "Statement": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Assignment": {"(", "id", "str", "num", "ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "while", "return", "print", "if", "for"},
    "If_Statement": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "If_Statement_Tail": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Else_If_Statements": {"ε", "else"},
    "Else_If_Statement": {"ε", "elseif"},
    "Optional_Else": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Else_Statement": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "While_Statement": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "For_Statement": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Return_Statement": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Function_Call": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "Arguments": {")"},
    "Arguments_Tail": {")"},
    "Expression": {")", "==", "!=", "<", "<=", ">", ">=", ",", "ε", ";", "&&", "(", "id", "str", "num"},
    "Expression_Tail": {")", "==", "!=", "<", "<=", ">", ">=", ",", "ε", ";", "&&", "(", "id", "str", "num"},
    "Term": {"+", "-", "ε"},
    "Term_Tail": {"+", "-", "ε"},
    "Factor": {"*", "/", "ε"},
    "Conditions": {";", ")"},
    "Conditions_Tail": {";", ")"},
    "Condition": {"&&", "ε", "(", "id", "str", "num", ";", ")"},
    "Relational_Operator": {"(", "id", "str", "num"},
    "Print": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for"},
    "End_Line": {"ε", "int", "float", "char", "string", "bool", "big", "double", "small", "function", "id", "while", "return", "print", "if", "for", "(", "str", "num"},
    "Identifier": {"(", "=", "{", "ε", ";", "*", "/"},
    "string_literal": {"*", "/", "ε"},
    "Number": {"}", "*", "/", "ε"}
}



